meta_product_name: "AVC Task Manager"
meta_title: "AVC - Plan it, share it, enjoy it!"
meta_description: "A simple calendar and task tool that is a great digital replacement for paper-based schedules!"
meta_image: "cover.png" # should exist in `app/assets/images/`